version: '3'

services:
  web:
    build:
      context: .
      target: dev
    volumes:
      - .:/src
    container_name: nest_js_web
    stdin_open: true
    tty: true
    ports: 
      - 3000:3000
    env_file:
      .env
    depends_on:
      - db 
  db:
    image: postgres:13
    container_name: nest-db
    restart: 'no'
    ports:
      - '5432:5432'
    volumes:
      - pg_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file: .env

  pg_admin:
    container_name: pg_admin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  pg_db:
    
