version: '3'

services:
  web:
    build:
      context: .
      target: dev
    volumes:
      - .:/src
    container_name: nest_js_web
    stdin_open: true
    tty: true
    ports: 
      - 3000:3000
    env_file:
      .env
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: nest-db
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - 33066:3306
    volumes:
      - nest_db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 5001:8080

volumes:
  nest_db:
