###  Testing Endpoingts

GET http://localhost:3000

### 

POST http://localhost:3000/users
Content-Type: application/json

{
	"email": "Umess11234213@gmail.com", 
	"password": "abcd",
	"name": "Ram chaudhary"
}
