###  Testing Endpoingts

GET http://localhost:3000

### 

POST http://localhost:3000/users
Content-Type: application/json
{
	"name": "Umesh",
	"email": "umesschaudhary@gmail.com", 
	"password": "Akash@1111"
}
